name: test

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@v3
      
    - name: Maximize build disk space
      uses: easimon/maximize-build-space@v4
        
    - name: Sync 
      run: |
        df -h
        export CCACHE_COMPRESS=1
        export USE_CCACHE=1
        git config --global user.name "adrian-8901"
        git config --global user.email "adrianlam230@gmail.com"
        mkdir ~/fluid
        cd ~/fluid
        sudo apt-get install git
        git clone https://github.com/akhilnarang/scripts.git ~/script
        cd ~/script
        bash setup/android_build_env.sh
        cd ~/fluid
        repo init --depth=1 --no-repo-verify -u https://github.com/Project-Fluid/manifest.git -b fluid-11 -g default,-device,-mips,-darwin,-notdefault
        git clone https://github.com/adrian-8901/.repo-local_manifest.git --depth 1  .repo/local_manifests
        repo sync  -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune
        
    - name: Build 
      run: |
        cd ~/fluid
        source build/envsetup.sh
        lunch fluid_umi-eng
        export WITH_GAPPS=true
        export SELINUX_IGNORE_NEVERALLOWS=true
        export TZ=Asia/Hong_Kong
        mka init
        mka bootimg
        mka sepolicy

